name: Three Hours
favicon: null
layout_spectrum: 0.75799
typography_spectrum: 0.66505
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040000'
    - '#504d48'
    - '#cb801b'
    - '#fcc32a'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
