name: Three Hours
favicon: null
layout_spectrum: 0.34584678313694894
typography_spectrum: 0.7810398086439818
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9741445297840983
  lightness: 0.6113427623640746
  saturation: 0.07044545887038112
  rhythmicContrast: 0.22136449185200036
purpose: []
